version: "3.10"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "${Django_PORT}:${Django_PORT}"
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 3s
      timeout: 30s
      retries: 3
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  postgres_data:
